replicaCount: 1
image:
  repository: chartmuseum/chartmuseum
  tag: v0.1.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
ingress:
  enabled: true
  hostname: exmaple.org
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 80m
    memory: 64Mi
    
